### ISSUE TITLE
orbitControl() affects gui elements (webgl mode)

### ISSUE THREAD

**Issue by sean369see** [quarks/canvasGUI#1]
After updating to p5 1.60, GUI elements are now affected by orbitControl() and camera translations. Does not occur in p5js 1.50 where GUI elements stay fixed in place with orbitControl() only having an effect on the 3d model in the sketch.

**Comment by quarks** [comment]
The solution can be found in this [guide](https://github.com/quarks/canvasGUI/wiki/My%20first%20sketch%20using%20canvasGUI%20(part%202)) it requires the user to surround the 3D drawing part with push/pop like this
```
  p.draw = function () {
        p.push(); // save matrix
        p.orbitControl();
        
        p.background(210, 200, 255);
        // 3D drawing commands

        p.pop(); // restore matrix
        p.gui.draw();
    }
```

**Comment by sean369see** [comment]
orbitControl() does not work when you surround it in push() and pop(). My solution is to not use 1.60 or find an alternative for orbitControl().

**Comment by quarks** [comment]
I removed **_all_** references to canvasGUI from both the html and js file in the Ogro sketch. I then tried the sketch with both 1.5.0 and 1.6.0

`orbitControl()` worked using 1.5.0 but with 1.6.0 the display was vertically inverted (upside-down) when the mouse was pressed, which makes me believe that the problem is with p5.js and not canvasGUI 

With regard to 

> GUI elements are now affected by orbitControl()

The code I provided earlier solves this issue in that the controls position and functionality are not affected by `orbitControl()` using 1.6.0
